server:
  port: 8080

spring:
  application:
    name: leads-gateway-service

  cloud:
    gateway:
      routes:
        # User Service Route
        - id: user-service
          uri: lb://userservice   # must match Eureka serviceId
          predicates:
            - Path=/api/users/**

        # Order Service Route
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/api/orders/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # still handy for debugging

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
