server:
  port: 8080

spring:
  application:
    name: leads-gateway-service
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/api/users/**
          filters:
            - name: RateLimitFilter

        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/api/orders/**
          filters:
            - name: RateLimitFilter

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # still handy for debugging

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
