server:
  port: 8080

spring:
  application:
    name: leads-gateway-service
  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      routes:
        # User Service Route
        - id: user-service
          uri: lb://userservice   # must match Eureka serviceId
          predicates:
            - Path=/api/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 4
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"

        # Order Service Route
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/api/orders/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # still handy for debugging

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

   # if we create default for all microservice
#  cloud:
#    gateway:
#      default-filters:
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter.replenishRate: 2
#            redis-rate-limiter.burstCapacity: 4
#            redis-rate-limiter.requestedTokens: 1
#            key-resolver: "#{@userKeyResolver}"
